[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
'@solmate=lib/solmate/src/',
'@solmate/=lib/solmate/src/',
"forge-std/=lib/forge-std/src/"
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# defined to run howmany fuzztests usinng random id per test
[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config